name: change_project_name
description: >
  A CLI tool to rename Flutter/Dart projects and update all package references automatically.
  Simple, fast, and made for devs who hate tedious refactors.

version: 1.0.7
publish_to: https://pub.dev/publishers/itsyourboiputra.is-a.dev

repository: https://github.com/anugrahsputra/change_project_name
homepage: https://itsyourboiputra.is-a.dev
issue_tracker: https://github.com/anugrahsputra/change_project_name/issues
documentation: https://github.com/anugrahsputra/change_project_name#readme

topics:
  - cli
  - flutter
  - dart
  - rename
  - refactor

environment:
  sdk: ^3.9.0

dependencies:
  path: ^1.9.0
  yaml: ^3.1.3
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  change-project-name: change_project_name
